services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD:Admin@123
      - MYSQL_DATABASE:employee
      - MYSQL_USER:root
      - MYSQL_PASSWORD:Admin@123
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-scripts:/usr/lib/db-scripts
volumes:
  mysql_data: